name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.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 }}
        TARGET_REPO: anngreen1/anngreen1.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm run docs:dev
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://www.anngreen.icu
